# Generated by Django 4.0.1 on 2022-02-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('portfolio_mv', models.IntegerField()),
                ('cash', models.IntegerField()),
                ('total_deposits', models.IntegerField()),
                ('dividends', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
    ]
