# Generated by Django 4.0.1 on 2022-02-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='todolist',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
