# Generated by Django 4.0.1 on 2022-02-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='Portfolio', max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
