# Generated by Django 4.0.1 on 2022-02-07 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_name_alter_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 7, 8, 21, 55, 695966)),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('ticker', models.CharField(max_length=5)),
                ('shares', models.IntegerField()),
                ('avg_cost', models.IntegerField()),
                ('date', models.DateField()),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.position')),
            ],
        ),
    ]
