# Generated by Django 4.0.1 on 2022-02-07 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_position_date_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 7, 13, 23, 43, 130869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 7, 13, 23, 43, 130869, tzinfo=utc)),
        ),
    ]
