# Generated by Django 4.0.1 on 2022-02-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_watchitem_name_watchitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchitem',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
