# Generated by Django 4.0.1 on 2022-02-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_watchitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchitem',
            name='name',
        ),
    ]
