# Generated by Django 4.0.1 on 2022-02-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_watchitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='total_deposits',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='avg_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='shares',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='avg_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shares',
            field=models.FloatField(default=0),
        ),
    ]
