# Generated by Django 4.0.1 on 2022-02-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_watchitem_curr_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchitem',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
