# Generated by Django 4.0.1 on 2022-02-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_watchitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchitem',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
